# Generated by Django 5.1.6 on 2025-03-26 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcosMainHeaderPicturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header_title', models.CharField(blank=True, max_length=255, null=True)),
                ('main_header_description', models.TextField()),
                ('main_header_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('main_header_excos_img', models.ImageField(upload_to='main_images/')),
                ('main_header_excos_publish_date', models.DateTimeField(auto_now_add=True)),
                ('main_header_excos_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['main_header_excos_publish_date'],
            },
        ),
    ]
