# Generated by Django 5.1.6 on 2025-03-26 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0002_excosmainheaderpicturepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcosMainHeaderPicturePost',
            new_name='MainHeaderPicturePost',
        ),
    ]
