# Generated by Django 5.1.6 on 2025-03-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0003_rename_excosmainheaderpicturepost_mainheaderpicturepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainheaderpicturepost',
            old_name='main_header_excos_img',
            new_name='main_header_img',
        ),
    ]
