# Generated by Django 5.1.6 on 2025-03-26 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0004_rename_main_header_excos_img_mainheaderpicturepost_main_header_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoPicturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='logo_images/')),
                ('logo_publish_date', models.DateTimeField(auto_now_add=True)),
                ('logo_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['logo_publish_date'],
            },
        ),
    ]
