# Generated by Django 5.1.6 on 2025-03-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0006_excosuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excosuser',
            old_name='excos_user_url',
            new_name='excos_user_linkedIn_url',
        ),
    ]
