# Generated by Django 5.1.6 on 2025-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0007_rename_excos_user_url_excosuser_excos_user_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='excosuser',
            name='excos_user_img',
            field=models.ImageField(default=1, upload_to='excos_images/'),
            preserve_default=False,
        ),
    ]
