# Generated by Django 5.1.6 on 2025-03-29 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0009_whypsnypg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsnypgNewsAndEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psnypg_news_and_event_title', models.CharField(max_length=255)),
                ('psnypg_news_and_event_description', models.TextField()),
                ('psnypg_news_and_event_date', models.CharField(max_length=255)),
                ('psnypg_news_and_event_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('psnypg_news_and_event_img', models.ImageField(upload_to=' psnypg_news_images/')),
                ('psnypg_news_and_event_publish_date', models.DateTimeField(auto_now_add=True)),
                ('psnypg_news_and_event_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['psnypg_news_and_event_publish_date'],
            },
        ),
    ]
