# Generated by Django 5.1.6 on 2025-03-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0010_psnypgnewsandevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excospicturepost',
            options={'ordering': ['-excos_publish_date']},
        ),
        migrations.AlterModelOptions(
            name='excosuser',
            options={'ordering': ['-excos_user_publish_date']},
        ),
        migrations.AlterModelOptions(
            name='logopicturepost',
            options={'ordering': ['-logo_publish_date']},
        ),
        migrations.AlterModelOptions(
            name='mainheaderpicturepost',
            options={'ordering': ['-main_header_excos_publish_date']},
        ),
        migrations.AlterModelOptions(
            name='psnypgnewsandevent',
            options={'ordering': ['-psnypg_news_and_event_publish_date']},
        ),
        migrations.AlterModelOptions(
            name='whypsnypg',
            options={'ordering': ['-why_psnypg_publish_date']},
        ),
    ]
