# Generated by Django 5.1.6 on 2025-03-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0011_alter_excospicturepost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excosuser',
            options={'ordering': ['excos_user_publish_date']},
        ),
    ]
