# Generated by Django 5.1.6 on 2025-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0012_alter_excosuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excospicturepost',
            options={'ordering': ['excos_publish_date']},
        ),
        migrations.AddField(
            model_name='excospicturepost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
