# Generated by Django 5.1.6 on 2025-03-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0013_alter_excospicturepost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excospicturepost',
            name='title',
        ),
    ]
