# Generated by Django 5.1.6 on 2025-03-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0014_remove_excospicturepost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excospicturepost',
            name='excos_img',
            field=models.ImageField(upload_to='home_excos_img'),
        ),
    ]
