# Generated by Django 5.1.6 on 2025-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0015_alter_excospicturepost_excos_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='excospicturepost',
            name='excos_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
