# Generated by Django 5.1.6 on 2025-03-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnypg', '0016_excospicturepost_excos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='excosuser',
            name='excos_user_img_2',
            field=models.ImageField(default=1, upload_to='excos_images_2/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excosuser',
            name='excos_user_img_3',
            field=models.ImageField(default=1, upload_to='excos_images_3/'),
            preserve_default=False,
        ),
    ]
